#!/usr/bin/env python3
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    pogit                                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmoussou <mmoussou@student.42angouleme.fr  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/16 13:58:26 by mmoussou          #+#    #+#              #
#    Updated: 2024/02/16 13:58:26 by mmoussou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# ------------ credits ------------

__author__ = "y-syo"
__version__ = "0.5.0"
__license__ = "WTFPL"

# ------------ modules ------------

import sys
import os

# ------------ help messages ------------

class Colors:
    """ ANSI color codes """
    BLACK = "\033[0;30m"
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    BROWN = "\033[0;33m"
    BLUE = "\033[0;34m"
    PURPLE = "\033[0;35m"
    CYAN = "\033[0;36m"
    LIGHT_GRAY = "\033[0;37m"
    DARK_GRAY = "\033[1;30m"
    LIGHT_RED = "\033[1;31m"
    LIGHT_GREEN = "\033[1;32m"
    YELLOW = "\033[1;33m"
    LIGHT_BLUE = "\033[1;34m"
    LIGHT_PURPLE = "\033[1;35m"
    LIGHT_CYAN = "\033[1;36m"
    LIGHT_WHITE = "\033[1;37m"
    BOLD = "\033[1m"
    FAINT = "\033[2m"
    ITALIC = "\033[3m"
    UNDERLINE = "\033[4m"
    BLINK = "\033[5m"
    NEGATIVE = "\033[7m"
    CROSSED = "\033[9m"
    END = "\033[0m"

class Help:
    pogit = f'''{Colors.GREEN}pogit{Colors.END}

{Colors.BLUE}USAGE:{Colors.END}
  {Colors.ITALIC}pogit [COMMAND] ...{Colors.END}

{Colors.BLUE}OPTIONS:{Colors.END}
  {Colors.GREEN}-h, --help{Colors.END}        show this help message and exit.
  {Colors.GREEN}-v, --version{Colors.END}     print version.

{Colors.BLUE}COMMANDS:{Colors.END}
  {Colors.GREEN}c/commit{Colors.END}          Commit changes to the git repo.
  {Colors.GREEN}r/remote{Colors.END}          Manage the remotes of the repository.
  {Colors.GREEN}p/push{Colors.END}            Push the current project to all of the remotes.
  {Colors.GREEN}h/help{Colors.END}            Get help on a command.
'''
    push = f'''{Colors.GREEN}pogit remote push{Colors.END}
{Colors.BLUE}USAGE:{Colors.END}
  {Colors.ITALIC}pogit remote push <branch>{Colors.END}
'''
    commit = f'''{Colors.GREEN}pogit commit{Colors.END}

{Colors.BLUE}USAGE:{Colors.END}
  {Colors.ITALIC}pogit commit <message> -f <files> -d <denominator>
  pogit c <type> <(optional)denominator> <message>{Colors.END}

{Colors.BLUE}TYPE:{Colors.END}
  what's this commit about.

    {Colors.GREEN}feature/feat:{Colors.END}  「✨」 feat(_): added a very cool feature !
    {Colors.GREEN}clean:{Colors.END}         「🗑️」 clean(_): cleaned project.
    {Colors.GREEN}init:{Colors.END}          「🎉」 init(_): hello world !
    {Colors.GREEN}norm:{Colors.END}          「✏️」 norm(_): normed project.
    {Colors.GREEN}test:{Colors.END}          「🚧」 test(_): testing things, might broke.
    {Colors.GREEN}wip:{Colors.END}           「🏗️」 wip(_): work in progress, not done yet.
    {Colors.GREEN}fix:{Colors.END}           「🔨」 fix(_): fixed some things.
    {Colors.GREEN}doc:{Colors.END}           「📝」 doc(_): added documentation.

{Colors.BLUE}OPTIONS:{Colors.END}
  {Colors.GREEN}-f <files>{Colors.END}       which files should be inclued with the commit, by default, nothing will be staged.
  {Colors.GREEN}-d <denominator>{Colors.END} a prefix for the commit to point out what's the subject of the commit.

{Colors.BLUE}MESSAGE:{Colors.END}
  More precise description of the commit.
  If no message is given, there will be a default message.
'''

# ------------ global variables ------------

COMMANDS = ["commit", "push", "help", "--version", "c", "p", "h", "-v"]

C_TYPES = {"feature": "「✨」 feat",
           "feat": "「✨」 feat",
           "clean": "「🗑️」 clean",
           "init": "「🎉」 init",
           "norm": "「✏️」 norm",
           "test": "「🚧」 test",
           "wip": "「🏗️」 wip",
           "fix": "「🔨」 fix",
           "doc": "「📝」 doc"}

default_commit_msg = {"feature": "added a very cool feature !",
                      "feat": "added a very cool feature !",
                      "clean" : "cleaned project.",
                      "init" : "hello world !",
                      "norm" : "normed project.",
                      "test" : "testing things, might broke.",
                      "wip" : "work in progress, not done yet.",
                      "fix" : "fixed some things.",
                      "doc" : "added documentation."}


# ------------ commands functions ------------

def commit():
    if len(sys.argv) < 3 or sys.argv[2] not in C_TYPES:
        print(Help.commit)
        exit(0)
    c_type = sys.argv[2]
    c_denom = ""
    c_msg = ""
    c_final = ""
    files = ""
    args = sys.argv
    if "-f" in args:
        files = ' '.join(args[args.index("-f") + 1].split(','))
        args.pop(args.index("-f") + 1)
        args.pop(args.index("-f"))
    if "-d" in args:
        c_denom = args[args.index("-d") + 1]
        args.pop(args.index("-d") + 1)
        args.pop(args.index("-d"))

    if (len(args) == 3):
        c_msg = default_commit_msg[c_type]
    else:
        c_msg = ' '.join(args[3:])

    if (c_type not in C_TYPES):
        print("Error: type is not valid.")
        exit(0)
    c_final += C_TYPES[c_type]
    if (c_denom):
        c_final += ("(" + c_denom + ")")
    c_final += (": " + c_msg)
    if files:
        #print(f'git add {files}')
        os.system(f'git add {files}')
    #print(f'git commit -m "{c_final}"')
    os.system(f'git commit -m "{c_final}"')


def get_git_repo(dir):
    while (dir != "/"):
        if (".git" in os.listdir(dir)):
            return dir
        os.chdir('..')
        dir = os.getcwd()

def remote_list():
    #remotes = os.listdir(os.getcwd() + "/.git/refs/remotes")
    #for remote in remotes:
    #    print(remote)
    file = open(get_git_repo(os.getcwd()) + "/.git/config")
    remotes=[]
    for line in file:
        if "[remote" in line:
            remotes.append(line[9:-3])
    file.close()
    return (remotes)

def push():
    if (len(sys.argv) > 3):
        print("Error: Bad usage.")
        exit(0)
    if (len(sys.argv) == 3):
        branch = sys.argv[2]
    else:
        branch = "master"
    remotes = remote_list()
    for remote in remotes:
        os.system("git push " + remote + " " + branch)


def man():
    if (len(sys.argv) != 3 or sys.argv[2] not in COMMANDS):
        print(Help.pogit)
        exit(0)
    match (COMMANDS.index(sys.argv[2]) % (len(COMMANDS) / 2)):
        case 0:
            print(Help.commit)
        case 1:
            print(Help.push)
        case 2:
            print(Help.init)
        case _:
            print(Help.pogit)


# ------------ main function ------------

def check_git_repo(dir):
    while (dir != "/"):
        if (".git" in os.listdir(dir)):
            return True
        os.chdir('..')
        dir = os.getcwd()
    return False
        

def main():
    if (len(sys.argv) < 2 or sys.argv[1] == '-h' or sys.argv[1] == '--help' or sys.argv[1] not in COMMANDS):
        print(Help.pogit)
        sys.exit(0)
    arg = sys.argv[1]
    if (arg == '-v' or arg == '--version'):
        print("pogit v" + __version__)
        sys.exit(0)
    #if (".git" not in os.listdir(os.getcwd())):
    if not check_git_repo(os.getcwd()):
        print(f"{Colors.RED}are you sure you're in a git repository ?{Colors.END}")
        exit(0)
    match (COMMANDS.index(arg) % (len(COMMANDS) / 2)):
        case 0:
            commit()
        case 1:
            remote()
        case 2:
            push()
        case 3:
            man()
        case _:
            print(Help.pogit)


if __name__ == '__main__':
    main()
